# Generated by Django 5.0.3 on 2024-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_finch_breed_feeding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='finch',
        ),
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Feeding Date'),
        ),
    ]
